from: settings.countries
description: Country management hub to add, activate, and access country configuration.
relations:
  - to: settings.country.stages
    relation: parent-child
  - to: settings.country.regions
    relation: parent-child
  - to: settings.country.academic-years
    relation: parent-child
  - to: settings.country.subjects
    relation: parent-child
  - to: settings.country.calendar
    relation: parent-child
  - to: settings.country.weekdays
    relation: parent-child
  - to: settings.country.notifications
    relation: parent-child
  - to: settings.country.entity-registration
    relation: parent-child

